baseURL = "https://www.ryanbrushett.com"
title = "ryan brushett"
languageCode = "en-gb"
defaultContentLanguage = "en-gb"
theme = "hugo-coder"
paginate = 10

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "I'm Ryan"
  description = "It's my blog"
  info = "I write code but I do other things too"
  keywords = "blog,developer,personal"
  gravatar = "ryanbrushett@gmail.com"

  hideCredits = true
  hideCopyright = true
  since = "2020"

  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/RyanBrushett"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/ryanbrushett/"
[[params.social]]
  name = "Flickr"
  icon = "fa fa-flickr"
  weight = 3
  url = "https://flickr.com/photos/ryanbrushett"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram"
  weight = 4
  url = "https://instagram.com/ryanbrushett"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon"
  weight = 5
  url = "https://ruby.social/@ryanbrushett"
  rel = "me"
